#!/bin/sh
echo
echo "--- PostRemove * IPK Scripting v1.0 - date 10.02.2021 ---"
echo
echo "A shell script which is executed after uninstallation of the package:"
echo
echo "Name: XCplugin v1.7 for OEOE2.0"
echo
echo "uninstall XCplugin ..."


rm -rf /usr/lib/enigma2/python/Plugins/Extensions/XCplugin &> /dev/null

if [ ! -d /usr/lib/enigma2/python/Plugins/Extensions/XCplugin ]; then
     echo
     echo "Plugin Successfully Removed."
fi
echo
exit 0
